---
title: "통계 전반적인 부분 필사"
author: "Young Jae Kim"
date: '2022-03-15'
output:
  html_document:
    keep_md: true
categories:
- Machinelearning
- 통계
tags:
- Machinelearning
- 통계
---

# 분석방법
통계는 수량 데이터에서 다양한 방법으로 새로운 사실들을 찾아내는 학문입니다. 통계를 알아야 하는 이유는 사실을 확인하고,새로운 내용을 알아내기 위해서 입니다. 빅데이터를 분석할 때 기초적인 통계 지식을 아느냐,모르느냐에 따라 분석능력에 큰 차이가 생깁니다. 통계지식이 없으면 심각한 오류를 범할 수 있습니다. 실제로는 두 집단의 평균에서 차이가 없는데도 있다고 차이가 있다고 판단하는 경우가 대표적인 오류입니다. 통계에는 크게 두 종류가 있습니다.

# 1)기술통계
### 분산값이 크다->평균으로부터 멀어진 개별적인 데이터가 많다
### 분산값이 작다-<평균주위에 개별적인 데이터가 적다 
빅데이터 분석에서는 기본적으로 알아야 하는 값들이 있습니다.평균,최솟값,최댓값,중앙값과 같이 데이터의 특징을 알려주는 값들입니다. 이런 값들은 기술통계 라고합니다. 데이터의 특징을 서술한다는 의미입니다. 기술통계는 사실확인에 해당됩니다. 



# 2)추론통계 
변수간의 관계를 파악하고, 이를 토대로 변수간의 인과관계나 새로운 사실들을 밝혀내는 것을 추론통계 라고 합니다.
데이터 분석에서 하는 추론통계에는 평균 차이 검정, 교차분석,상관관계 분석, 회귀분석 등이 있습니다

##### 1)평균차이검정
집단별로 평균의 차이가 실제로 있는가를 검정하는 것입니다. 한 고등학교에서 3학년 학생들이 국어 시험을 보았는데,남학생 집단의 평균은 82.1점이고, 여학생 집단 평균은 82.3점 입니다. 여학생 집단이 남학생 집단보다 0.2점 높습니다. 그렇다고 여학생 집단의 성적이 남학생 집단보다 높다고 단정할 수 있을까요? 과거에는 남학생 집단의 평균이 여학생 집단의 평균보다 높은 적이 있었습니다. 그렇다면 이번에는 우연히 여학생 집단의 평균이 높았을 수도 있습니다. 때문에 이번 성적 결과가 "의미 있다", 즉, "여학생 집단의 평균성적이 남학생 집단보다 일반적으로 높다" 고 결론을 내리기 위해서는 먼저 이번 성적의 결과가 우연하게 발생한 것이 아니라는 것을 통계적으로 검정해야 합니다. 

#### 2)교차분석
범주형 변수로 구성된 집단들의 관련성을 검정하는 통계 분석입니다. 교차분석은 카이제곱검정,카이스퀘어검정,독립성 검정이라고도 합니다
한 아ㅏ트 단지에 100세대가 살고 있습니다. 집 크기는 소형이 50세대,대형이 50세대입니다. 이 단지의 TV 크기는 소형,대형 등 두 종류입니다. 집이 크면 대형 TV를 보유하고, 집이 작으면 소형 TV 를 보유하는지 , 즉 집의 크기와 TV 크기가 관계가 있는지를 통계적으로 분석하는 것이 교차 분석 검정입니다. 아파트 크기와 TV 크기는 모두 범주형 이어서 평균차이 검정을 할 수 없습니다. 

 분석결과는 관계가 있다, 없다 등 2가지입니다. 확률적으로는 이 단지의 TV 보유 상황은 소형 50대, 대형50대인 것으로 생각할 수 있습니다. 그런데 90세대가 대형TV를 보유하고, 10세대가 소형 TV를 보유하고 있다면, 아파트 크기와 TV 크기는 관계가 없습니다. 이런 경우는 "아파트 크기와 TV 크기는 독립적이다" 또는 "아파트 크기에 따라 TV 크기의 차이는 없다" 고 합니다. 그러나 55세대가 대형 TV를 보유하고 있고, 45세대가 소형TV를 보유하고 있으면 아파트 크기와 TV 크기는 관계가 있다고 추론할 수 있습니다. 이런경우 "아파트 크기와 TV 크기는 독립적이지 않다" 또는 "아파트 크기에 따라서 TV 크기는 차이가 있다" 고 합니다. 교차분석의 검정의 목적은 두 변수 사이에 관계가 있다는 것을 알아보는 것 입니다. 
 
#### 3)상관관계 분석
상관관계분석은 변수 간의 상관관계를 알아보는 것입니다. 상관관계는 변수간의 연관성입니다. 한 변수가 변화하면 다른 변수도 변화하는 관계입니다. 집합에서 여러 집단들이 교차해 있는 공집합의 관계를 생각하면 됩니다. 상관관계에서는 관계의 강도와 방향이 중요합니다. 강도는 한 변수가 변화할 떄 다른변수가 변화하는 정도입니다. 방향은 한 변수가 변화할 때 다른 변수가 같은방향으로 변화하는지, 반대방향으로 변화하는지를 의미합니다. 

  변화의 강도와 방향을 나타나는 계수가 상관계수(r)입니다. 상관계수는 -1부터 1사이에 있습니다. 수치가 클수록 영향을 주는 강도가 큽니다 + 정의관계 - 부의관계 또는 역의관계에 있는 것을 의미합니다. 상관계수가 0.3 이면, 한 변수가 1단위 변화할 때 다른 변수가 0.3만큼 같은 방향으로 변화하는 것을 말합니다. 

##### 상관관계 계수 -1<r<1
상관관계가  절대값 0.7 이상이면 높은관계 0.4~0.7 미만이면 다소 높은 관계 0.2~0.4 이면 낮은 관계에 있다고 봅니다. 0.2 미만이면 거의 없다고 해석합니다 

#### (4)회귀분석
상관관계로는 변수들의 관계를 알 수는 있지만, 인과관계는 알 수 없습니다. 인과관계는 원인과 결과의 관계입니다. 한 변수가 다른 변수에 영향을 주는 것을 말합니다. 영향을 주는 변수는 독립변수 이고, 영향을 받는 변수는 종속변수 입니다. 독립변수와 종속변수 간의 인과관계를 분석하는 통계적 방법을 회귀 분석이라고 합니다 "월급이 증가하면 외식횟수가 늘어날 것" 이라고 가정하면 월급은 독립변수이고, 외식횟수는 종속변수입니다. 월급의 증감은 외식횟수에 미치는 영향을 확률적으로 분석하는 것이 회귀분석입니다. 사회과학에서 회귀분석은 통계 분석의 꽃이라고 불릴정도로 매우 중요한 통계분석입니다. 

회귀분에서 독립변수가 1개이면 단순회귀분석, 2개이상이면 다중회귀분석이라고 합니다. 단순회귀분석은 1차함수 y=a+bx 에서 b를 찾아내는 것 입니다. x가 1증가하면, y는 b만큼 증가합니다. b를 회귀계수라고 합니다. x는 독립변수, y는 종속변수 a는 상수입니다.
회귀분석에서 a는 저련이라고 하는데, 통계적인 의미는 없습니다.

다중회귀분석은 종속변수는 1개이며 독립변수가 복수인 경우입니다. 복수의 독립변수들이 종속변수에 영향을 주는 정도를 분석하는 겁니다.  

##### 단순회귀분석=y=a+bx
##### 종속회귀분석=y=a+bx1+bx2

# 통계검정

#### (1)가설
가설은 어떤 현상을 설명하기 위해서 가정하는 명제입니다.증명되지 않은 추정입니다. 가설에는 귀무가설과 대립가설이 있습니다. 귀무가설은 설정한 가설이 맞을 확율이 극히 적어서 처음부터 기각될 것으로 예상되는 가설입니다. 영가설 이라고도 합니다. 대립가설은 연구자가 검정하고자 하는 가설입니다. 통계 검정은 통계적인 방법을 이용해서 대립가설이 맞는가를 검정하는 것입니다. 
 두 집단의 평균 차이가 있는가를 알아보려 합니다. 평균 차이가 있는지를 검정하는 것이기 떄문에 귀무가설은 '평균 차이가 있다' 입니다. 
 
##### H0(귀무가설):두 집단의 평균 차이가 없다
##### H1(대립가설):두 집단의 평균 차이가 있다

#### 2)유의수준
가설검정의 결과는 유의수준에 의해 결정됩니다. 유의수준은 귀무가설이 맞는데도 대립가설을 채택할 확률입니다. 즉 오류를 범할 확률입니다. 차이가 없느넫도 있다고 할 확률입니다. 통계 분석에서는 P-VALUE(P값)로 제시됩니다. P값이 0.01이라면 오류를 범할 확률이 1%라는 의미입니다. 오류가 없는 것이 가장 좋겠지만, 현실적으로 오류가 없다는 것은 거의 불가능합니다. 통계에서도 오류가 있기 마련이어서 어느정도의 오류는 인정할 수밖에 없습니다. 그래서 허용할 수 있는 오류범위를 정하게 됩니다 유의수준 5%는 오류를 5%까지 허용하겠다는 으미입니다. 화살 100발을 쏘는 경우 유의수준 5%는 과녁을 벗어나는 화살이 5발 이내이면 합격한 것으로 보는 것입니다. 화살 1000발을 쏘면 50발 이내입니다. 
 허용하는 유의수준의 범위와 정확성은 반대의 개념입니다. 유의수준의 범위가 넓으면 연구결과를 얻기가 쉽지만 결과의 정확성이 떨어지고, 너무 좁으면 결과를 얻기 어렵습니다. 100점 만점 시험에서 90점 이상을 합격으로 할 떄와 80점이상을 합격으로 할때 합격자의 부노와 질적수준은 크게 달라집니다 90점 이상으로 하면 합격자의 평균점수는 높지만 합격자 수가 적습니다. 80점 이상으로 하면 합격자 수는 증가하지만 합격자의 평균점수는 낮아집니다. 
 가설검정에서 인정하는 유의수준에는 5%,1%,0.1%등 세 종류가 있습니다. 사회과학에서는 5%까지 인정합니다. 그러나 정확성이 많이 요구되는 자연과학이나 의학에서는 유의수준의 허용범위가 더욱 좁아집니다.
 통계 분석을 하면 결과물에는 유의수준(P-VALUE)이 적혀 있습니다. 통계 분석 결과를 해석할 떄는 먼저 유의수준이 0.05 이내인가를 보고, 결과가 통계적으로 유의미한지를 판단해야 합니다. 유의수준이 0.05 이상인데도 결과가 유의미하다고 해석되면 매우 심각한 오류입니다. 유의수준의 반대 개념은 신뢰수준 입니다. 신뢰할 수 있는 범위를 의미합니다. 유의수준 5% 이내라고 하면 신뢰수준은 95%입니다.

#### 척도
척도(scale)는 측정도구이며,수치로 표시됩니다. 척도에는 명목척도,서열척도,등간척도,비율척도 등 네 종류가 있습니다. 척도의 종류에 따라 통계분석이 가능하거나 불가능하기 때문에 분석하기 전에 척도의 종류를 파악해야합니다

명목척도:측정대상의 특성이나 범주를 구분하는 수치입니다. 운동선수의 번호를 생각하면 쉽습니다. 번호는 특정 선수를 의미합니다. 성을 분류할 때 통상 남자를 1번 여자를 2번으로 분류하는 것과 같이 결혼유무,종교,인종,지역,계절 등을 표시할 때도 이용됩니다. 산술연산을 할 수 없습니다.

서열척도:계급,사회계층,자격등급 등과 같이 측정대상의 등급순위를 나타내는 척도 입니다. 척도 간의 거리나 간격은 나타내지 않습니다. 산술연산을 할 수 없습니다.

등간척도:측정대상을 일정한 간격으로 구분한 척도입니다. 서열뿐만 아니라 거리와 간격도 표시합니다. 온도,학력,시험점수 등입니다. 덧셈과 뺄셈이 가능합니다.

비율척도:측정대상을 비율로 나타낼 수 있는 척도입니다. 연령,무게 등입니다. 모든 수로 측정할 수 있어 4칙연산이 가능합니다. 


# 통계분석 사례
#### 1)두 집단의 평균 차이 검정
남녀 등 두 딥단의 평균 차이를 분석할 때는 독립표본 t검정을 합니다. R에서는 내장된 t.test()함수로 합니다. 독립변수는 명목척도이며, 종속변수는 등간척도 또는 비율척도 이어야 합니다. t.test() 함수를 쓰는 방식은 2가지가 있습니다. 


###### 방법1) t.test(data=데이터세트,종속변수~독립변수)

###### 방법2) t.test(데이터세트$종속변수~데이터세트$독립변수)

### 예제를 통해 알아보자
예제파일인 mpg1.csv의 trans 변수에는 기어변속방법으로 auto 와 manaual 등 두 방식이 있습니다.두 방식에 따라 cty평균이 통계적으로 유의미한 차이가 있는가를 알아보겠습니다. cty는 도시에서 1갤런당 달리는 거리입니다. 독립변수는 trans 이며, 종속변수는 cty입니다. 가설은 다음과 같이 설정합니다

#### 귀무가설:auto와 manual의 cty 평균은 차이가 없다.

#### 대립가설:auto와 manual의 cty 평균은 차이가 있다.

```r
mpg1<-read.csv("mpg1.csv",stringsAsFactors = FALSE)
t.test(mpg1$cty~mpg1$trans)
```

```
## 
## 	Welch Two Sample t-test
## 
## data:  mpg1$cty by mpg1$trans
## t = -4.5375, df = 132.32, p-value = 1.263e-05
## alternative hypothesis: true difference in means between group auto and group manual is not equal to 0
## 95 percent confidence interval:
##  -3.887311 -1.527033
## sample estimates:
##   mean in group auto mean in group manual 
##             15.96815             18.67532
```
t.test 평균 차이 검정을 해석해 보자면 p-vaue가 1.263/100000 값이 나왔으므로, 95 percent confidence interval 이 뜻은 신뢰수준이 95% 라는 뜻이고, 그렇게 되면 유의수준이 5% 이기때문에, 0.05보다 매우 작기 때문에 유의수준 허용조건을 충족 시켰다. alternative hypothesis: true difference in means between group auto and group manual is not equal to 0  이 뜻은 대립가설:평균 차이가 있다 라는 뜻 입니다. 
sample estimates 를 보면 auto의 평균이 15.96  manual 의 평균이 18.675 인것을 보아도 알 수 있다. 
결론을 쓸때는 "cty 평균거리는 자동식이 15.97마일, 수동식이 18.68마일이다. 유의 수준(p)이 0.05 보다 작아서 통계적으로 유의미한 차이가 있기 때문에 수동식 평균이 자동식의 평균보다, 약2.7마일 길다고 할 수 있다" 고 하면 됩니다. '길다' 라고 단정적으로 쓰지 않고 '길다고 할 수 있다'라고 추론식으로 쓴 것은 확률을 토대로 한 추론분석이기 때문입니다. 
 
만약 p-value가 .05보다 크면 "유의수준이 0.05 보다 크기 때문에 자동식과 수동식의 평균은 통계적으로 유의미한 차이가 없다" 라고 쓰면 됩니다.


#### 2)교차분석
교차분석은 범주형 변수들이 관계가 있다는 것을 입증하는 것입니다. 평균의 차이가 아니라,비율에 차이가 있는지를 검정합니다.교차분석 검정은 R의 chisq.test() 함수로 합니다. 
# 교차분석 나중에 다시 해보기 

##### 귀무가설:trans 에 따라서 drv의 차이가 없다.
##### 대립가설:trans 에 따라서 drv의 차이가 있다.

우선 table() 함수와 prop.table() 함수로 교차분석을 해서 trans에 따른 drv의 빈도와 비율을 알아보아야한다.


#### 상관관계분석
상관관계 분석은 R에 내장되어 있는 cor.test() 함수로 합니다.
 mpg1 에는 cty 와 hwy가 있습니다 cty는 도시에서 1갤런당 달리는 거리이고 hwy는 고속도로에서 1갤런당 달리는 거리입니다. cty가 길면 hwy도 길 럿이라고 생각할 수 있습니다. 이 가설을 검정해 보겠습니다. 검정하려는 가설은 cty와 hwy는 서로 상관관계가 있다는 것이기 때문에 이것이 대립가설입니다. 귀무가설은 상관관계가 없다는 것 입니다. 
 
##### 귀무가설:cty와 hwy 는 상관관계가 없다.
##### 대립가설:cty와 hwy 는 상관관계가 있다.


```r
mpg1<-read.csv("mpg1.csv",stringsAsFactors = FALSE)
cor.test(mpg1$cty,mpg1$hwy)
```

```
## 
## 	Pearson's product-moment correlation
## 
## data:  mpg1$cty and mpg1$hwy
## t = 49.585, df = 232, p-value < 2.2e-16
## alternative hypothesis: true correlation is not equal to 0
## 95 percent confidence interval:
##  0.9433129 0.9657663
## sample estimates:
##       cor 
## 0.9559159
```
상관계수 결과를 해석하자면 pvalue 값이 매우작게 0.05 보다 작게 나왔으므로, 상관관계가 0이 아니다 라는 대립가설은 통계적으로 유의하고, 상관계수 값 또한 0.95 로 나왔기 때문에, 굉장히 높은 관계가 있다고 보면 된다.

### 4)회귀분석
##### 1)단순회귀분석
단순회귀분석은 독립변수가 1개,종속변수가 1개일 때 합니다. 회귀분석의 변수는 독립변수와 종속변수가 모두 등간척도 또는 비율척도이어야 합니다. 회귀분석은 R의 lm()함수로 합니다. 세 방법 중 어느 것을 써도 됩니다

lm(data=데이터세트,종속변수~독립변수)
lm(종속변수~독립변수,data=데이터세트)
lm(데이터세트$종속변수~데이터세트$독립변수)

Motor trend 라는 데이터로 실습을 해볼것 인데,disp(배기량)이 mpg(연비)에 미치는 영향을 분석하겠습니다. 

##### 귀무가설:disp 는 mpg에 영향을 끼치지 않는다
##### 대립가설:disp 는 mpg에 영향을 준다. 

```r
lm(data=mtcars,mpg~disp)
```

```
## 
## Call:
## lm(formula = mpg ~ disp, data = mtcars)
## 
## Coefficients:
## (Intercept)         disp  
##    29.59985     -0.04122
```
Coefficients 가 -0.04122 라는 뜻은 disp가 1단위 올라갈때마다 mpg는 -0.04122 만큼 떨어진다는 뜻 입니다. 이 베타를 회귀계수라고 하며 독립변수가 종속변수에 미치는 영향을 뜻 합니다. 
그런데 무언가 빠진 느낌입니다. 유의수준이 없다 유의수준을 보려면 lm() 의 결과를 summary()에 넣으면 세부분석이 나온다


```r
summary(lm(data=mtcars,mpg~disp))
```

```
## 
## Call:
## lm(formula = mpg ~ disp, data = mtcars)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -4.8922 -2.2022 -0.9631  1.6272  7.2305 
## 
## Coefficients:
##              Estimate Std. Error t value Pr(>|t|)    
## (Intercept) 29.599855   1.229720  24.070  < 2e-16 ***
## disp        -0.041215   0.004712  -8.747 9.38e-10 ***
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
## 
## Residual standard error: 3.251 on 30 degrees of freedom
## Multiple R-squared:  0.7183,	Adjusted R-squared:  0.709 
## F-statistic: 76.51 on 1 and 30 DF,  p-value: 9.38e-10
```
p-value 가 .05 보다 낮은것을 볼 수 있고 이렇게되면 회귀모형이 적합하다고 봅니다 반대로 .05 보다 크면 회귀모형에 문제가 있는 것이므로 회귀분석 자체가 성립되지 않습니다. 

R-squared 는 결정계수 라고 합니다. 회귀모델의 추정된 회귀식이 관측된 데이터를 설명하고 있는 비율을 계수로 나타낸 것 입니다. 결정계수는 상관계수(r) 을 제곱한 수치이며 r^2 로 표시합니다. 결정계수는 0과 1 사이에 있습니다 1에 가까울 수록 추정된 회귀선을 충족하는 표본 데이터가 많아서 추정된 회귀선의 예측 정확도와 변수 관계 설명력이 높다는 것을 의미합니다. 0에 가까울수록 회귀식과 맞지 않는 데이터가 많고, 추정된 회귀선의 예측 정확도와 변수 관계 설명력이 낮습니다. 여기서는 결정계수가 0.7183이므로 높습니다. Adjusted R-squared 는 '수정된 결정계수' 입니다. 결정계수는 데이터와 독립변수가 많을수록 회귀식의 예측력과 무관하게 커지는 경향이 있어서 이를 보완한 결정계수입니다. 연구 결과에서는 수정된 결정계수를 밝히는 것이 일반적입니다. 이분석에서 수정된 결정계수는 0.709 입니다. 분석 결과는 다음과 같이 적으면 됩니다. 
"회귀모형은 유의수준 p<.001 에서 적합하며, 회귀식의 수정된 결정계수는 .709 이다. 배기량이 연비에 미치는 회귀계수(B)는 유의수준 P<.001 에서 -0.04 이다"


#### 다중회귀분석
다중회귀분석은 종속변수에 영향을 주는 독립변수가 복수일때 분석하는 방식입니다. 여러 독립변수들은 서로 영향을 주면서 종속변수에 영향을 주기 때문에 한 독립변수가 종속변수에 미치는 영향력은 단순회귀분석을 했을 때와 다중회귀분석을 했을 때에 달라집니다. 다중회귀분석에서는 단순회귀분석의 독립변수들은 +기호로 연결합니다.

##### 방법1 lm(data=데이터세트,종속변수~독립변수1+독립변수2)

##### 방법2 lm(종속변수~독립변수1+독립변수2,data=데이터세트)

##### 방법3 lm(데이터$종속변수,데이터$종속변수1+데이$종속변수2)

mtcars 데이터로 실습하겠습니다. mpg에는 disp(배기량) 이외에도 hp(마력)와wt(중량)이 영향을 미칠 수 있습니다. 세 독립변수가 mpg에 어떤 영향을 주는지 알아보겠습니다.


```r
data("mtcars")

lm(data=mtcars,mpg~disp+hp+wt)
```

```
## 
## Call:
## lm(formula = mpg ~ disp + hp + wt, data = mtcars)
## 
## Coefficients:
## (Intercept)         disp           hp           wt  
##   37.105505    -0.000937    -0.031157    -3.800891
```

다중회귀식은 mpg=37+-0.000937 * disp - 0.031157 * hp - 3.800891 * wt 입니다. 그러나 세 독립변수의 회귀계수에 대한 유의수준이 없어서 회귀계수가 유의미한 지를 알 수 없습니다. summart() 함수로 유의수준을 비롯한 상세 결과를 알아보겠습니다.



```r
summary(lm(data=mtcars,mpg~disp+hp+wt))
```

```
## 
## Call:
## lm(formula = mpg ~ disp + hp + wt, data = mtcars)
## 
## Residuals:
##    Min     1Q Median     3Q    Max 
## -3.891 -1.640 -0.172  1.061  5.861 
## 
## Coefficients:
##              Estimate Std. Error t value Pr(>|t|)    
## (Intercept) 37.105505   2.110815  17.579  < 2e-16 ***
## disp        -0.000937   0.010350  -0.091  0.92851    
## hp          -0.031157   0.011436  -2.724  0.01097 *  
## wt          -3.800891   1.066191  -3.565  0.00133 ** 
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
## 
## Residual standard error: 2.639 on 28 degrees of freedom
## Multiple R-squared:  0.8268,	Adjusted R-squared:  0.8083 
## F-statistic: 44.57 on 3 and 28 DF,  p-value: 8.65e-11
```
먼저 맨아래 회귀모형의 p-value 는 8.65e-11 로 회귀모형은 적합하고, 
변수별로 본다면 hp와 wt 는 p-value 가 유의수준 보다 낮아 허용되지만 disp는 허용되지 않습니다
이는 disp 는 mpg에 영향을 주지 않고, hp와 wt만 영향을 줍니다. hp가 1단위 증가하면 mpg는 0.031157씩 감소하고, wt가 1단위씩 증가하면 mpg는 3.800891 씩 감소합니다. 앞의 단순회귀분석에서는 disp가 mgp에 정적인 영향을 주었는데, 다중회귀분석에서는 영향을 주지 않았습니다. 이같이 같은 독립변수라도 분석방법에 따라 영향력이 달라집니다. 결정계수를 보면 0.8083 으로 높아서 회귀모델의 설명력이 높습니다. 이상의 결과를 토대로 다음과 같이 적습니다
"회귀모형은 유의수준 p<.001에서 적합하며, 회귀식의 수정된 결정계수는.81 이다 3개 독립변수가 연비에 미치는 회귀계수 b는 hp가 .03,wt가*3.80 이었고 disp는 없었다. wt의 영향력이 가장 컸다" 

